dnsimple/erldns

- priv/zonefile.md
JSON was not correctly displayed. Added a missing comma.
> Fixed typo

- priv/example.zone.json
- priv/test.zones.json
- src/erldns_records.erl
- src/erldns_zone_encoder.erl
- src/erldns_zone_parser.erl
Adds support for the CAA record type.
> Implement CAA record type

- src/erldns_zone_cache.erl
- src/erldns_zone_loader.erl
> Do not suppress the backend storage error.

- src/erldns_worker.erl
> Drop messages that are received with the qr bit set to 1

- src/erldns_resolver.erl
DC/OS JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-5108
DC/OS PR: https://github.com/dcos/erldns/pull/5
RFC 1034 section 3.6 says that the order should be irrelevant, but some dns clients (e.g. glibc) expect to see CNAME records before A/AAAA records.
For more details please see a discussion about this issue in skydns: https://github.com/skynetservices/skydns/issues/217
The order of CNAME records in answer does also matter.
> CNAME records should appear before A/AAAA records.

- .travis.yml
- Procfile
- README.md
- Standardizes Procfile for [Overmind](https://github.com/DarthSim/overmind).
Also formats `README.md`
> Adds Procfile

- src/erldns_zone_cache.erl
Fix RRSet PUT to properly insert the named records into the zone_records storage.
> Soa missing after rrset delete and put

- src/erldns_handler.erl
* added additional handling of specific exceptions to propagate proper return codes for specific DNS queries
> * added additional handling of specific exceptions to propagate return codes back to requestor

- src/erldns_dnssec.erl
- src/sample_custom_handler.erl
adds map_nsec_rr_types function to allow for custom handlers
> * added map_nsec_rr_types

- .github/workflows/ci.yml
- .tool-versions
- LICENSE.md
- Also updates to latest OTP/25
- Removes OTP/24 as it' is EOL
> Update to OTP/26

- src/erldns_zone_cache.erl
This PR removes verify_zone() and verify_rrset() as the functions result is not in use.
> Clean up verify_zone() and verify_rrset() as the functions result is not in use

- BENCHMARKING.md
- README.md
Following my comment [here](https://github.com/dnsimple/erldns/pull/134#issuecomment-2395436635).
> Add a benchmarking guide

- .github/workflows/ci.yml
- .tool-versions
Moving to use `json` over `jsx` when possible is gonna happen in another PR so that this is an easy one to review!
> Update to OTP/27

- CONTRIBUTING.md
- Makefile
Part of https://github.com/dnsimple/dnsimple-ops/issues/4058.
> Check formatting in CI

- .tool-versions
See https://github.com/dnsimple/dnsimple-ops/issues/4218
Follow up from https://github.com/dnsimple/erldns/pull/161
> Use a specific X.Y.Z version

- README.md
Follows up https://github.com/dnsimple/erldns/issues/140
> Update README.md explaining AXFR (not) support

- .github/workflows/ci.yml
- Makefile
- rebar.config
- test/dnstest_SUITE.erl
Relates to https://github.com/dnsimple/erldnsimple/issues/426, uses https://github.com/dnsimple/dnstest/pull/17
> Add dnstest suite to CI

- .github/workflows/check_deps.yml
Fix PR body construction, a silly bug was clearing the output.
> Fix check_deps output

- src/erldns_handler.erl
According to https://github.com/dnsimple/erldnsimple/pull/153, these throws should have been handled at
https://github.com/dnsimple/erldns/pull/128/files#diff-00d51df0a163c180ad4a15efdf4f9539f09fcf20f166be65f85bc2b2c8e40225R190
Fixes infinite error logs as in https://app.datadoghq.com/logs?query=service%3Aerldnsimple%20filename%3Astructured.log&agg_m=count&agg_m_source=base&agg_t=count&clustering_pattern_field_path=message&cols=host%2Cservice&event=AwAAAZbN7slRBIrHOQAAABhBWmJON3VCdkFBRGw0bWRkemJ5UTBBQUEAAAAkMDE5NmNkZWYtMDExNS00NjFiLTg0YjItZjk5M2YyOWY3MzViAAAIYQ&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1747210687387&to_ts=1747211587387&live=true
> Fix throws as errors

- src/listeners/erldns_listeners.erl
- src/listeners/erldns_proto_tcp.erl
- src/listeners/erldns_proto_udp.erl
- test/listeners_SUITE.erl
Improve documentation and add a function to get statistics about the current state of listeners.
> Stats and docs

- src/zones/erldns_zone_cache.erl
- test/zones_SUITE.erl
Fixes https://github.com/dnsimple/erldnsimple/issues/518.
> Fix matching on a non normalised clause

- src/admin/erldns_admin.erl
- src/admin/erldns_admin_zone_control_handler.erl
- src/admin/erldns_admin_zone_records_resource_handler.erl
- src/admin/erldns_admin_zone_resource_handler.erl
- src/erldns_app.erl
- src/erldns_dnssec.erl
- src/erldns_handler.erl
- src/listeners/erldns_encoder.erl
- src/listeners/erldns_proto_tcp.erl
- src/listeners/erldns_proto_udp.erl
- src/listeners/erldns_proto_udp_acceptor.erl
- src/pipes/erldns_empty_verification.erl
- src/pipes/erldns_pipeline.erl
- src/pipes/erldns_resolver.erl
- src/zones/erldns_zone_cache.erl
- src/zones/erldns_zone_codec.erl
- src/zones/erldns_zone_encoder.erl
- src/zones/erldns_zone_loader.erl
- src/zones/erldns_zone_parser.erl
Closes https://github.com/dnsimple/erldnsimple/issues/471
> Logger domains

- CHANGELOG.md
Collapse changes from release candidates into a single section.
> Prepare release v7.0.0

- src/pipes/erldns_resolver.erl
- test/listeners_SUITE.erl
Just adding a line of coverage and saving one `to_labels` during ns zonecut resolution.
> Coverage and minor resolver improvements

- test/zones_SUITE.erl
This PR adds a testcase simulates that simuulates a situation when the zone needs to be updated even without the SOA record present. This may happen for example during an Inbound AXFR.
> Test cache update without SOA
