dnsimple/erldns

- src/erldns_app.erl
- src/erldns_event_handler.erl
- src/erldns_worker.erl
Handles error responses from `inet:peername` and tracks them.
> Handle TCP error when getting the socket peername.

- priv/test.zones.json
- src/erldns_zone_cache.erl
The idea is to support querying for a user-defined top-level domain. Currently, I am able to create the top-level domain and associated records but unable to query from clients like `dig`. The use-case is for localized service discovery similar to [Consul](https://www.consul.io/docs/agent/dns.html).
> Support Top-level domains

- src/erldns.app.src
- src/erldns_udp_server.erl
Some OS's (solaris for example) require to set `{reuseaddr, true}` on UDP connections when you want to open multiple UDP listeners on the same connection. This PR adds it as a default option to the UDP socket creation.
A change in the app.src snuck in here, it adds mnesia as a dependency (since it is).
> Add udp reuse addr

- src/erldns_config.erl
- src/erldns_resolver.erl
- src/print_delegate.erl
Adding support for delegating failed lookups as discussed in #45 
* Delegation can be specified per-zone
* Delegation only happens if there is neither a cached record nor a record in the normal configuration
* Has a low overhead when not used - If no delegates are configured this adds a overhead of: 1 x application:get_env + 1x lists:keyfind([])
> Add support for delegating zone lookups

- rebar.config
boundary/folsom is now unmaintained, use folsom-project/folsom instead.
> Use folsom-project instead of boundary for folsom

- src/erldns_zone_cache.erl
erldns_zone_cache.erl:131 returns **authority_not_found**, instead of **no_authority**
> erldns_zone_cache:get_authority() spec mismatch

- src/erldns_zone_cache.erl
Interface of `put_zone/1` function was changed in [this](https://github.com/aetrion/erl-dns/commit/81ba350ae7ad3dad67c780872d0c2028a3c4159e#diff-8a8e060b9a8de98f1aa024db2afad89bL183) commit.
> Add compatibility with earlier versions

- .travis.yml
- include/erldns.hrl
- src/erldns_zone_cache.erl
I've changed data structure for named index because of performance reasons. `build_named_index/2` was super slow for a zone with thousands of records. Here is a small performance test:
```
$ ./run.sh
> rr("include/erldns.hrl").
> R = #dns_rr{name = <<"s">>, type = 1, ttl = 3600, data = #dns_rrdata_a{ip = {127, 0, 0, 1}}}.
> RR = [ R#dns_rr{name = <<(integer_to_binary(N))/binary, ".p">>} || N <- lists:seq(0, 1000000)].
> Zone = {<<"test">>, <<>>, RR, []}.
> timer:tc(fun () -> erldns_zone_cache:put_zone(Zone) end).
```
I've got 12 minutes for master branch and 11 seconds for my version.
> Use maps for named index

- src/erldns_app.erl
- src/erldns_storage_mnesia.erl
- src/erldns_sup.erl
- src/erldns_tcp_server.erl
- src/erldns_udp_server.erl
- src/erldns_worker.erl
- src/erldns_worker_process.erl
- src/erldns_worker_process_sup.erl
Previous to this change, a significant number of long-running requests could cause worker mailboxes to become too large to process effectively. With this change workers call worker_process(ers) with a specific timeout, and if the timeout is reached, the worker will terminate the existing worker_process(er) and restart it.
> Introduce timeouts to provide more control over long-running requests

- priv/test.zones.json
CDS0 and CDNSKEY0 are special forms of the CDS/CDNSKEY records that specify that DNSSEC is turned off. According to the RFC, they are
```
CDS 0 0 0 0
CDNSKEY 0 3 0 0
```
This adds these zones to the test.zones.json file to have examples for querying:
`dig -p 8053 @localhost example-dnssec0.com -t cds`
`dig -p 8053 @localhost example-dnssec0.com -t cdnskey`
Important to note that CDS digest is hex-encoded ("00") and CDNSKEY public key is base64 encoded ("AA==").
> Example zone for CDS0 and CDNSKEY0

- priv/test.zones.json
- src/erldns_resolver.erl
When responding to a question for a record under a [zonecut](https://tools.ietf.org/html/rfc2181#section-6), we should only return an authority section that points to the authoritative servers.
There are two primary behaviors implemented:
* If a record is queried that is under a zonecut, do not send back answer, only authority
* If a CNAME record is queried, DO send back answer if pointing to a name in the zone (we are authority).
This behavior is tested in [dnstest](https://github.com/dnsimple/dnstest/pull/2).
This PR implements a solution that is not optimized, but does implement the desired behaviour. Expectation is that a new PR will be created to handle optimization.
> Properly handle zonecuts

- src/erldns_config.erl
- src/erldns_server_sup.erl
DC/OS JIRA: https://jira.mesosphere.com/browse/DCOS_OSS-1946
DC/OS PR: https://github.com/dcos/erldns/pull/3
The patch allows to run erldns as a library with no tcp/udp servers.
> Allow to run erldns in headless mode.

- .travis.yml
- priv/scapy.txt
- src/erldns_app.erl
- src/erldns_decoder.erl
- src/erldns_encoder.erl
- src/erldns_event_handler.erl
- src/erldns_handler.erl
- src/erldns_resolver.erl
- src/erldns_storage.erl
- src/erldns_udp_server.erl
- src/erldns_worker.erl
- src/erldns_worker_process.erl
- src/erldns_zone_cache.erl
- src/erldns_zone_encoder.erl
- src/erldns_zone_loader.erl
- src/erldns_zone_parser.erl
Important events that occur in the erldns application now fire events, allowing better handling of error and info.
> Switch from logging to events

- src/erldns_storage.erl
- src/erldns_storage_mnesia.erl
- src/erldns_zone_cache.erl
Mnesia related changes addressing https://github.com/dnsimple/erldns/issues/102.
Addressing Mnesia backend failing on erldns_zone_cache functions:
* added type bag on table creation (zone_records, zone_records_typed)
* set explicit type set on table creation (zones)
* refactored select/3: using ETS match spec converted to Mnesia's
match_object pattern
* using different pattern in erldns_zone_cache:zone_names_and_versions/0
depending on backend (ETS/Mnesia foldl/3 return values are different)
>  Addressing Mnesia backend failing on erldns_zone_cache functions

- .gitignore
- rebar.config
- rebar.lock
- src/erldns.app.src
- src/erldns_app.erl
- src/erldns_storage_mnesia.erl
* Adds Nodefinder as a dependency.
On startup, if there are other nodes in the cluster the mnesia storage will replicate from the other nodes.  
Multiple nodes will then have all records synced between them.
* Create directories for two mnesia storage locations for example: one and two
* Enable mnesia storage backend in erldns.config.
```
{erldns
{storage, [
{type, erldns_storage_mnesia},
{dir, "./one"}
]
}
}
{mnesia,
[
{dir, "./one"}
]},
```
```
rebar3 shell --sname one --setcookie dns
```
* Edit erldns.config to run on a different port (e.g. 8054)
* Change the storage location for mnesia to the second location you created ("./two").
* Empty the priv/example.zone.json to only contain "[]"
```
rebar3 shell --sname two --setcookie dns
```
Test that both nodes respond with the first node …
> Distributed Mnesia

- src/erldns_zone_cache.erl
Fixes https://github.com/dnsimple/erldnsimple/issues/131
This PR fixes management of RRSIG record sets during RRSet put and delete operations. It removes the deletion operation before the put and fixes RRSIG management in the delete operation.
> Fix bugs with RRSIG management on RRSet put and delete operations

- src/erldns_storage_json.erl
- src/erldns_storage_mnesia.erl
- src/erldns_zone_cache.erl
This PR removes the use of the `zone_records` ETS table in favor of applying all reads and writes to the `zone_records_typed` table, removing the need for duplicate data and making it easier to apply RRSet changes.
> Remove zone_records in favor of zone_records_typed

- src/erldns_event_handler.erl
- src/erldns_handler.erl
- src/erldns_resolver.erl
- src/erldns_worker.erl
- src/erldns_zone_cache.erl
This change causes NXDOMAIN to be returned early in the resolve process when the following is true:
1. The qname is not present in the zone, either directly or via a wildcard match.
2. The CNAME chain is empty
This PR also moves various log entries out of gen_event handlers and back to the point where the event originally occurs.
> Short circuit when qname is not found in the zone's record set

- src/erldns_zone_encoder.erl
Enhance the erldns zone encoder so it has additional functions for encoding only the zone meta data, and encoding specific record sets.
Supports https://github.com/dnsimple/erldns-admin/pull/5
> Zone encoder function for metadata only

- src/erldns_zone_parser.erl
erldns usage of JSON relies on implicit ordering of keys which is the JSON equivalent of C's undefined behaviour.
The first commit dealing with zonefiles is a reasonable approach, but the 2nd commit for DNSSEC keys could be improved - suggestions welcomed!
For that commit, I tried to preserve the existing behaviour that parses all fields in a single pass, but this introduces a risk of an infinite loop around the final clause if any keys are missing/extra (and therefore the previous pattern match fails).
> fix json key ordering

- src/erldns_storage.erl
- src/erldns_zone_loader.erl
I'm using erldns inside another project where I have a jsx version
incompatibility, we just add a simple test here and you can bump
jsx as you prefer without issue.
- tested with OTP 22.3.4.2
- works with jsx 2.10.0 and 3.0
```
Finished in 1.697 seconds
33 tests, 0 failures
```
> replaces PR#107 which was done off my master branch sorry
> jsx: v3.x uses maps unless proplists are explicitly forced

- src/erldns_config.erl
- src/erldns_worker.erl
* externalized ingress UDP request timeout to configuration variable (ingress_udp_request_timeout)
* externalized ingress TCP request timeout to configuration variable (ingress_tcp_request_timeout)
> Externalized ingress UDP and TCP request timeouts to configuration variables

- rebar.config
- src/erldns_zone_cache.erl
The PR introduces optimizations for large zones:
1. Optimise delegation lookup ETS queries by dropping wildcard in the matchspec for `get_delegated/1` function.
2. Drop named index on zone update via RRSet.
> Optimise delegation lookup ETS queries and drop named index on zone update

- rebar.config
- rebar.lock
GitHub has strengthened its security requirements by deprecating unencrypted `git://` protocol and certain keys that are also no longer supported for more information you can read their [announcement](https://github.blog/2021-09-01-improving-git-protocol-security-github/).
> Update deps to new accepted uri

- rebar.config
- rebar.lock
Github has discontinuted the git:// protocol in favor of only providing https for anonymous clones.
```
$ DEBUG=1 rebar3 get-deps
...
===> Fetching dns_erlang (from {git,"git://github.com/dnsimple/dns_erlang.git",
{ref,"52f7279afb4cc97b4d76babde223257ec08f3676"}})
===> sh(git clone  -n git://github.com/dnsimple/dns_erlang.git .tmp_dir967982599246)
failed with return code 128 and the following output:
Cloning into '.tmp_dir967982599246'...
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
===> Failed to fetch and copy dep: {git,
"git://github.com/dnsimple/dns_erlang.git",
{ref,
"52f7279afb4cc97b4d76babde223257ec08f3676"}}
```
Reference: …
> rebar: Use https:// instead of git:// for github deps

- src/erldns.app.src
- src/erldns_worker.erl
This is needed even in environments where opentelemetry itself isn't
enabled, as it provides the interface for erldns to define its traces.
Without this, erldns_worker would crash when processing queries, as the
opentelemetry module doesn't exist:
```erlang
{'module could not be loaded',
[{opentelemetry,get_tracer,[erldns_worker],[]},
{erldns_worker,handle_cast,2,
[{file,".../erldns/src/erldns_worker.erl"},
{line,69}]},
```
Note: I didn't notice this issue when starting my application using rebar3 shell; it was only when I deployed using a release (rebar3 release) this started to occur, so I assume it has to do with how the modules included in the release are collected. Without this change, relx wouldn't know to include the `opentelemetry` module (provided by the `opentelemetry_api` …
> Start opentelemetry_api otp application

- src/erldns_udp_server.erl
Reset the `{active, N}` socket option only when receiving an `udp_passive` message, rather than on every received packet, which provides no flow control and therefore no advantage over `{active, true}` mode.  (BTW, resetting `{active, N}` actually _adds_ `N` to the current count, so adding `100` on every packet could in theory overflow the counter at some point.)
> erldns_udp_server: Fix flow control

- src/erldns_zone_parser.erl
It doesn't take a binary, it takes a map or proplist (and soon only a map when the `json` move continues).
> Fix spec for `erldns_zone_parser:zone_to_erlang/1`

- src/erldns_zone_parser.erl
Define helper function to call the genserver with a custom timeout when doing a zone parse using `zone_to_erlang/2`.
> Add zone_to_erlang/2 allowing for custom timeout when parsing zone

- .github/workflows/check_deps.yml
We hadn't done this yet in this repo, resulting in failing workflow runs.
> Add correct permissions to GitHub Actions

- .github/workflows/release.yml
The current workflow doesn't work for OTP > 24. This change aligns with the other open source repo.
> CI: Update Release workflow

- priv/zones-example.json
- src/admin/erldns_admin.erl
- src/admin/erldns_admin_zone_records_resource_handler.erl
- src/erldns_zone_encoder.erl
- src/metrics/erldns_metrics.erl
- test/admin_endpoint_SUITE.erl
Relates to https://github.com/dnsimple/erldns/pull/192, adds some tests to it and fixes a couple of bugs:
- Authentication would crash if the provided token wasn't of the same length.
- DNSSEC would fail to build a json file when fetching over the admin API because the key wouldn't be a valid JSON tag and would fail to convert to JSON. I suspect this bug to be very very old.
> Test admin endpoint

- src/erldns_dnssec.erl
The new API might be needed from dependants in their testing.
> Fix exporting an unsupported map_nsec_rr_types

- .github/workflows/check_deps.yml
Add `rebar3 upgrade --all` to correctly upgrade dependencies. Also ensure the committer and author are the github bot.
Relates to https://github.com/dnsimple/dnsimple-engineering/issues/256
> Update update_deps in CI

- src/erldns_handler.erl
This gen_server is called for handlers on _every_ single request, when the handlers could be just stored on ets tables that incur next to no contention at runtime.
> Avoid hot-code calls to a cache gen_server by using an ets table

- src/erldns_worker.erl
As described [here](https://github.com/dnsimple/chef-dnsimple_erldnsimple/pull/415#issuecomment-2893335620), this creates an event with the current mailbox size of the worker processes that is triggered on every new message process, which gives an idea of the pending amount of work.
> Create worker mailbox length telemetry event

- src/zones/erldns_zone_parser.erl
- test/zone_parser.erl
According to RFC4032 §3.1.5, these timestamps are supposed to be expressed in seconds.
Unfortunately, in commit 88670b3cc4ac6f9ef3d8da9fd7fe1789153bc4d7 (merged at 1ab1f8da91ace3cd62974c573bbce3be595cccb4), we parsed this value in milliseconds.
The issue is fixed and regression tests are added for providing valid RFC3339 timestamps in all possible time units.
> Fix incident related to wrong DNSSEC timestamps

- src/zones/erldns_zone_cache.erl
- test/zones_SUITE.erl
The codec decode function returns zone records, hence this function should be accepting them.
> Have cache put_rrset_zone accept zone records as put_zone

- include/erldns.hrl
- rebar.config
- src/admin/erldns_admin.erl
- src/erldns.erl
- src/erldns_handler.erl
- src/listeners/erldns_listeners.erl
- src/listeners/erldns_proto_tcp.erl
- src/listeners/erldns_proto_udp.erl
- src/listeners/erldns_proto_udp_acceptor.erl
- src/listeners/erldns_sch_mon.erl
- src/pipes/erldns_packet_cache.erl
- src/pipes/erldns_pipeline_worker.erl
- src/pipes/erldns_query_throttle.erl
- src/zones/erldns_zone_codec.erl
- src/zones/erldns_zone_encoder.erl
- src/zones/erldns_zone_loader.erl
- src/zones/erldns_zone_parser.erl
- src/zones/erldns_zones.erl
Note that the directory was not wildcard matching children dirs and therefore there were many modules that were not being linted.
Fixes for the ignored errors will come with later PRs.
> Apply new elvis rules to further directories

- CHANGELOG.md
- erldns.example.config
- rebar.config
- src/pipes/erldns_dnssec.erl
- src/pipes/erldns_pipeline.erl
- src/pipes/erldns_query_throttle.erl
- src/pipes/erldns_resolver.erl
- src/pipes/erldns_resolver_recursive.erl
- src/pipes/erldns_section_counter.erl
- src/pipes/erldns_sorter.erl
- test/dnstest_SUITE.erl
Split dnssec, sorter, and recursion flags, from erldns_resolver.
Also move RRSIG records from being refused to being throttled.
> Split erldns_resolver

- src/zones/erldns_zone_cache.erl
- test/zones_SUITE.erl
Closes https://github.com/dnsimple/erldnsimple/issues/548.
Note that the SOA record is stored twice: once in the zones table (the `authority` section of the `#zone{}` record), and another one as a standalone RRSet in the typed records table. And then the resolution algorithm would use the RRSet in the typed records table as the answer for an explicit query to SOA records but the cached ones on the zone record for any other query that required including SOA records. This would be an issue for DNSSEC, because for example an NSEC answer would include the RRSIG record of the _new_ SOA record, but with the _old_ SOA record, hence triggering a validation failure.
Note that this code [was available in v7](https://github.com/dnsimple/erldns/blob/0d1a717458fc6554c1a1765a5f1d2a381245f3ef/src/zones/e …
> Fix bug with SOA records not updating correctly

- src/zones/erldns_zone_cache.erl
When deleting records, an empty list could be a value for an RRSIG record that would be put in the cache. This could happen even if the zone had no DNSSEC enabled. The current implementation would create and insert an empty RRSIG record even if there wasn't one before. I believe the correct implementation just discards the RRSIG record instead of inserting a new one with an empty value.
Because of how the "getters" from ETS worked (for example [pattern_zone_dname/2](https://github.com/dnsimple/erldns/blob/899b0fdbcc0be5edef14c037a227cfa706e6f2b2/src/zones/erldns_zone_cache.erl#L753-L755)) by appending the resulting record list, this empty RRSIG record would not appear usually. However, it would get counted as an existing record, which could lead to bugs. Specifically for the ENT rework to …
> Do not put empty RRSIG record values in the cache
